name: Deploy to Pantheon Dev

on:
  push:
    branches:
      - #default-branch#

jobs:
  deploy-dev:
    name: Build and push
    uses: ./.github/workflows/pantheon-push.yml
    with:
      pantheon-branch: master
      artifact: '#default-artifact#'
    secrets:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
