pantheon:
  git-repo-regex: '/^ssh:\/\/codeserver\.dev\.[a-f0-9\-]+@codeserver\.dev\.[a-f0-9\-]+\.drush\.in:2222\/~\/repository\.git$/'
  site-info:
    id: ~
    name: ~
  terminus:
    machine-token: ~
    bin: terminus
    default-site-name: ${pantheon.site-info.name}
  multidev:
    default-source-env: dev
